version: '3.3'
services:
    app:
        container_name: verre-tech
        build: 1.0
        ports: 
            -8080:8080
        restart: on-failure
        volumes:
            - seller:/home/vt/seller/
        depends_on: 
            - fullstack-postgres
        networks:
            - fullstack


    postgres:
        image: postgres:latest
        container_name: db_postgres
        environment:
            - POSTGRES_USER=${vtuser}  
            - POSTGRES_PASSWORD=${vt2020@oid78}
            - POSTGRES_DB=${verre_tech}
            - DATABASE_HOST=${localhost} 
        ports:
            - '5432:5432'
        volumes:
            - database_postgres:/var/lib/postgresql/data
        networks:
            - fullstack
        restart: unless-stopped

    volumes:
        api: 
        database_postgres:  

    networks:
        fullstack:
            driver: bridge