version: '3.3'
services:
    app:
        container_name: verre-tech
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - 8081:8081
        # restart: on-failure
        volumes:
            - store:/store
        depends_on: 
            - postgres
        networks:
            - fullstack


    postgres:
        image: postgres:latest
        container_name: db_postgres
        environment:
            - POSTGRES_USER=vtuser  
            - POSTGRES_PASSWORD=vt2020@oid78
            - POSTGRES_DB=verre_tech
            - DATABASE_HOST=localhost 
        ports:
            - '5432:5432'
        volumes:
            - database_postgres:/var/lib/postgresql/data
        networks:
            - fullstack
        restart: unless-stopped

volumes:
    store: 
    database_postgres:  

networks:
    fullstack:
        driver: bridge